version: "3.7"

services:
  tellerbot:
    build:
      context: .
      args:
        ESCROW_ENABLED: ${ESCROW_ENABLED}
    container_name: tellerbot
    depends_on:
      - database
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ${DATABASE_PASSWORD_FILENAME}:${DATABASE_PASSWORD_FILENAME}:ro
      - ${TOKEN_FILENAME}:${TOKEN_FILENAME}:ro
      - ${ESCROW_FILENAME}:${ESCROW_FILENAME}:ro
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  database:
    image: mongo:latest
    container_name: ${DATABASE_HOST}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=${DATABASE_PASSWORD_FILENAME}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    command: mongod --port ${DATABASE_PORT} --quiet
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ${DATABASE_PASSWORD_FILENAME}:${DATABASE_PASSWORD_FILENAME}:ro
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./data/db:/data/db
